### ISSUE TITLE
Sitecore 9.2 Feature Branch Disables SSL Certificate Validation

### ISSUE THREAD

**Issue by jpspringall** [Aceik/Sitecore-Speedy#14]
Hey @TomTyack 

I was looking at the Sitecore 9.2 Feature Branch code for an unrelated issue, and noticed the following:

![image](https://user-images.githubusercontent.com/477087/153330285-1aefa7f9-f115-420d-bbb5-bac1d8ba264f.png)

The line: ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;
If my understanding is correct, this will disabled SSL certificate validation globally as it will always return true

I'm presuming that this is for dev purposes, so would it make sense to either:
a) Make it so only gets applied if you are in development mode
b) Create a completely new setting to Enable/Disable SSL Certificate Validation

Cheers

J

**Comment by jpspringall** [comment]
Just noticed this is also mentioned #12 Did you ever implement it?

**Comment by TomTyack** [comment]
Hi James, 

This is patched up in master and in the 9.2 Retro fit branch.  I haven't repackaged new zip releases for these changes. 

FYI the retro fit of functionality were branches that I did after special requests from people in Slack. Features and code built for Sitecore 10 was ported back in these branches.  Full disclosure, not a whole lot of testing was done on those branches. 

Tom.
