### ISSUE TITLE
Sitecore 9.2 DownloadCssFile RestSharp Reference

### ISSUE THREAD

**Issue by jpspringall** [Aceik/Sitecore-Speedy#15]
Hi @TomTyack 

We are going through a bit of pain with RestSharp, as version 105.2.3 doesnt have a public key token, so it doesnt play nice with binding redirects.

Would you have an objection with swapping the RestSharp reference for the WebClient as in master:

 WebClient client = new WebClient();
string reply = client.DownloadString(host + url);

Cheers

J

**Comment by TomTyack** [comment]
Hi James, 

Yeah makes sense.  Done in both master and 9.2 Retro fit branches.

Note: I haven't repackaged new zip releases for these changes.
The retro fit of functionality were branches that I did after special requests from people in Slack. Features and code built for Sitecore 10 was ported back in these branches. Full disclosure, not a whole lot of testing was done on those branches.

Tom.
