### ISSUE TITLE
SXA 10.0.0 Body undefined after cached and Font Icons are not encoded properly

### ISSUE THREAD

**Issue by zarahquiray** [Aceik/Sitecore-Speedy#18]
Hello,

We have integrated this module to our solution and the solution always seem to work in my local instance but not when deployed to higher environments.

1. Body is not defined the second time you refresh the page (when the page has been cached). We get errors on sxa ootb scripts . Have you experienced this on your end
![image](https://user-images.githubusercontent.com/73168282/160586874-14ab17c6-9429-445a-a128-84619e02e2fe.png)

2. Fonts are not encoded properly in critical css. We are using font awesome from core libraries and when added to the stylesheet, the font content are not encoded as expected (left is the one deployed and right is in my local)
![image](https://user-images.githubusercontent.com/73168282/160587433-1fa61670-13e4-4e55-8fd4-0c4c830c3922.png)

Hope you can help me, thanks!

**Comment by TomTyack** [comment]
Hi @zarahquiray ,

I can't say I have seen this issue before. 

If you change the layout back to the default SXA one and test the page again, does everything work again?

Regards,
Thomas.

**Comment by zarahquiray** [comment]
Hi @TomTyack , disabling speedy or changing back the layout to default makes everything work again.

For Fonts, I just removed the font generated in crit css by using filter css, and added the working font in the important css. 
The Javascript, however, I am still looking for a workaround.

**Comment by TomTyack** [comment]
Noted thanks for letting me know.  

I guess speedy code is interfering with normal asset delivery somehow.  Potentially inside of 
 /master/src/Foundation/Speedy/code/Speedy/SpeedyAssetLinksGenerator.cs

I actually don't have access to a partner license for testing anymore, unfortunately, so am a bit stuck to fix it right now. 

Similar issue noted in: https://github.com/Aceik/Sitecore-Speedy/issues/16

**Comment by zarahquiray** [comment]
I will pull the the dll from #16 , and let you know the result. Thanks!!

**Comment by zarahquiray** [comment]
@TomTyack  unfortunately, just removing the package reference doesnt work.
I debugged more in higher environment, and find this behavior strange

**Ctrl+f5** -> the system works
**Adding breakpoint to the script** -> the system works

Is moving the javascript loader at the bottom of the body an idea?

**Comment by zarahquiray** [comment]
@TomTyack moving the loader at the bottom of the body works. Although I don't know the impact of this would be.
![image](https://user-images.githubusercontent.com/73168282/161494066-ded94411-f3ec-4f49-a6a0-5d3a2e8193e9.png)

Would you know?
