### ISSUE TITLE
Speedy settings section doesn't appear on page settings on Sitecore 9.3

### ISSUE THREAD

**Issue by shararehl** [Aceik/Sitecore-Speedy#6]
Hi,
I am trying to use Sitecore Speedy with Sitecore 9.3. I have downloaded Sitecore Speedy 9.3 and installed it on my local sitecore. But once applied to a page, the Speedy section doesn't appear. Any thoughts?

**Comment by TomTyack** [comment]
Hi @shararehl ,

Sorry about the late reply. 

I have released a version supporting 9.3 with all the improvements and refinements made for Sitecore 10. 

https://github.com/Aceik/Sitecore-Speedy/releases/tag/v9.3_RetroFit

The application of the addition buttons is no longer relevant in V2 of speedy.  We found content editors couldn't really be bothered maintaining critical CSS when the layout changed. So now its an all or nothing approach in the latest version. 

I haven't extensively tested this release, but do let me know of any issues if they pop up.
