### ISSUE TITLE
Sitecore 9.2 - doesn't work on CD, trying to get master database

### ISSUE THREAD

**Issue by alexanderkay** [Aceik/Sitecore-Speedy#7]
Got this on Sitecore 9.2 SXA CD environment:

![image](https://user-images.githubusercontent.com/40399476/113779699-1b5df700-96fc-11eb-9e74-9d012a5686ac.png)

**Comment by SaraTenorio** [comment]
The problem previously reported in 9.2 also happens in Sitecore 10
![image](https://user-images.githubusercontent.com/51181210/115008768-6ec20900-9ea3-11eb-9445-685e63e98499.png)
Sendo assim, não é possível utilizar desta solução em ambientes web

**Comment by SaraTenorio** [comment]
@alexanderkay X look at this link and confirm if your problem is solved.
https://github.com/Aceik/Sitecore-Speedy/issues/8#issuecomment-822025504

**Comment by TomTyack** [comment]
Thanks Guys, will try to look into this shortly and get an update out for 9.2

**Comment by TomTyack** [comment]
[https://github.com/Aceik/Sitecore-Speedy/releases/tag/9.2](https://github.com/Aceik/Sitecore-Speedy/releases/tag/9.2)   [Sitecore.Speedy.v2.0.1-release-92_retro_fit.zip](https://github.com/Aceik/Sitecore-Speedy/releases/download/9.2/Sitecore.Speedy-v2.0-release-92_retro_fit.zip)

Updated the above release with fixed DLL.  Also dropped in instructions for CD servers into the package readme. 

Thanks again for the feedback.
