### ISSUE TITLE
Sitecore 10 - doesn't work on CD, trying to get master database

### ISSUE THREAD

**Issue by SaraTenorio** [Aceik/Sitecore-Speedy#8]
The problem previously reported in 9.2 also happens in Sitecore 10
![image](https://user-images.githubusercontent.com/51181210/115009041-c1032a00-9ea3-11eb-9307-c718ae92b506.png)
Therefore, it is not possible to use this solution in web environments

**Comment by SaraTenorio** [comment]
@TomTyack and @JasonHorne

**Comment by SaraTenorio** [comment]
### @TomTyack and @JasonHorne 

Regarding the code, a solution was verified and validated, as shown below.

**Changes**:

_- SpeedyConstants.cs_
Include the string "Web" within the struct Database
![image](https://user-images.githubusercontent.com/51181210/115154021-b2b63900-a070-11eb-95fb-c731a4416fe9.png)

_- SpeedyGenerationSettings.cs_
1. Change the "GetGlobalSettingsItem", "GetCookieExpiration" and "IsDebugModeEnabled" methods; 
2. And include the "GetWebDatabase" method;
![image](https://user-images.githubusercontent.com/51181210/115154050-cfeb0780-a070-11eb-9d1f-f6d81e63dc2e.png)


_- SpeedyAssetLinksGenerator.cs_
Change the "BuildEntireCssBlock" method
![image](https://user-images.githubusercontent.com/51181210/115154026-bc3fa100-a070-11eb-92b1-9d3931ce2389.png)

I believe that this change also solves the issue reported in Sitecore 9.2 
> Issue [#7 ]

**Comment by TomTyack** [comment]
Thanks for this.  Give me some time to verify. 

I believe this same bug was fixed in the later version. So I might be able to back port it to 9.2

**Comment by TomTyack** [comment]
Bug fix release:  https://github.com/Aceik/Sitecore-Speedy/releases/tag/V10.0.0

Also added specific instructions to the package on what needs to be done to replicate deployment on CD.
